const { contextBridge, ipcRenderer, webUtils } = require('electron')

contextBridge.exposeInMainWorld('BocomHermes', {
  // 窗口
  spawnCard: (title) => ipcRenderer.invoke('spawn-card', title),
  startConversation: (payload) => ipcRenderer.invoke('start-conversation', payload),
  getCardFiles: (id) => ipcRenderer.invoke('get-card-files', id),
  spawnFanout: (goal) => ipcRenderer.invoke('spawn-fanout', goal),
  spawnFanoutRoles: (goal, roles) => ipcRenderer.invoke('spawn-fanout-roles', { goal, roles }),
  getFanoutRoles: () => ipcRenderer.invoke('get-fanout-roles'),
  closeSelf: () => ipcRenderer.send('close-self'),
  hideSelf: () => ipcRenderer.send('hide-self'),
  minimizeSelf: () => ipcRenderer.send('minimize-self'),
  getSelfBounds: () => ipcRenderer.sendSync('get-self-bounds'),
  setSelfBounds: (b) => ipcRenderer.send('set-self-bounds', b),
  togglePin: () => ipcRenderer.invoke('toggle-pin'),
  toggleMaximize: () => ipcRenderer.invoke('toggle-maximize'),
  // 主题
  getTheme: () => ipcRenderer.sendSync('get-theme'),
  setTheme: (t) => ipcRenderer.send('set-theme', t),
  onTheme: (cb) => ipcRenderer.on('theme-changed', (_e, t) => cb(t)),
  // 项目目录
  getProject: () => ipcRenderer.sendSync('get-project'),
  pickProject: () => ipcRenderer.invoke('pick-project'),
  setProjectDir: (dir) => ipcRenderer.invoke('set-project-dir', dir),
  pickBackend: () => ipcRenderer.invoke('pick-backend'),
  clearBackend: () => ipcRenderer.invoke('clear-backend'),
  onProject: (cb) => ipcRenderer.on('project-changed', (_e, p) => cb(p)),
  // 设置面板
  openSettings: () => ipcRenderer.invoke('open-settings'),
  getSettings: () => ipcRenderer.sendSync('get-settings'),
  setSettings: (patch) => ipcRenderer.invoke('set-settings', patch),
  // MCP 注册到 opencode/bocomcode 的 opencode.json
  mcpRegisterStatus: () => ipcRenderer.invoke('mcp-register-status'),
  mcpRegister: (targetPath) => ipcRenderer.invoke('mcp-register', targetPath || null),
  // OceanBase 测试连接
  dbTest: () => ipcRenderer.invoke('db-test'),
  // 卡坞 / 会话历史
  openDock: () => ipcRenderer.invoke('open-dock'),
  getHistory: () => ipcRenderer.sendSync('get-history'),
  openHistory: (sid, title) => ipcRenderer.invoke('open-history', { sid, title }),
  clearHistory: () => ipcRenderer.invoke('clear-history'),
  // 工作流（动态编排）
  spawnWorkflow: (goal) => ipcRenderer.invoke('spawn-workflow', goal),
  runWorkflow: (goal) => ipcRenderer.invoke('run-workflow', goal),
  abortWorkflow: () => ipcRenderer.send('abort-workflow'),
  wfApprove: (reqId, decision, auto) => ipcRenderer.send('wf-approve', { reqId, decision, auto }),
  onWorkflowEvent: (cb) => ipcRenderer.on('wf-event', (_e, p) => cb(p)),
  // 需求分析（多Agent 对抗 → 三类清单）
  openReqAnalysis: () => ipcRenderer.invoke('open-req-analysis'),
  pickReqDocPath: () => ipcRenderer.invoke('pick-req-doc-path'),
  pickReqRepo: () => ipcRenderer.invoke('pick-req-repo'),
  reqAnalyze: (docPath) => ipcRenderer.invoke('req-analyze', docPath),
  reqAbort: () => ipcRenderer.send('req-abort'),
  onReqEvent: (cb) => ipcRenderer.on('req-event', (_e, p) => cb(p)),
  openReqConfirm: (reportId) => ipcRenderer.invoke('open-req-confirm', reportId),
  getReqReport: (reportId) => ipcRenderer.invoke('get-req-report', reportId),
  exportReqReport: (reportId) => ipcRenderer.invoke('export-req-report', reportId),
  reqLandfill: (reportId, decisions) => ipcRenderer.invoke('req-landfill', { reportId, decisions }),
  // 出详设（实施方案）
  reqPlan: (reportId, decisions) => ipcRenderer.invoke('req-plan', { reportId, decisions }),
  onReqPlanEvent: (cb) => ipcRenderer.on('req-plan-event', (_e, p) => cb(p)),
  openReqPlan: (reportId) => ipcRenderer.invoke('open-req-plan', reportId),
  getReqPlan: (planId) => ipcRenderer.invoke('get-req-plan', planId),
  exportReqPlan: (planId) => ipcRenderer.invoke('export-req-plan', planId),
  // 对话 ↔ opencode 会话
  cardInit: (opts) => ipcRenderer.invoke('card-init', opts || {}),
  onCardInject: (cb) => ipcRenderer.on('card-inject', (_e, p) => cb(p)),
  onCardNote: (cb) => ipcRenderer.on('card-note', (_e, p) => cb(p)),
  cardSend: (text, files) => ipcRenderer.invoke('card-send', (files && files.length) ? { text, files } : text),
  cardReinit: () => ipcRenderer.invoke('card-reinit'),
  parseDoc: (path) => ipcRenderer.invoke('parse-doc', path),
  // 取拖入文件的本地路径:Electron 34 已移除 File.path,改用 webUtils.getPathForFile
  getDropPath: (file) => { try { return webUtils.getPathForFile(file) } catch (e) { return (file && file.path) || '' } },
  listModels: () => ipcRenderer.invoke('list-models'),
  cardSetModel: (m) => ipcRenderer.invoke('card-set-model', m),
  cardAbort: () => ipcRenderer.send('card-abort'),
  onStream: (cb) => ipcRenderer.on('card-stream', (_e, p) => cb(p)),
  onServeHealth: (cb) => ipcRenderer.on('serve-health', (_e, p) => cb(p)),
  onServeProbe: (cb) => ipcRenderer.on('serve-probe', (_e, p) => cb(p)),
  getProbeLog: () => ipcRenderer.invoke('get-probe-log'),
  probeNow: () => ipcRenderer.invoke('probe-now'),
  openLoc: (file, line) => ipcRenderer.invoke('open-loc', { file, line }),
  applyDiff: (diffText) => ipcRenderer.invoke('apply-diff', diffText),
  onPermission: (cb) => ipcRenderer.on('permission-request', (_e, p) => cb(p)),
  permissionReply: (requestId, decision) => ipcRenderer.send('permission-reply', { requestId, decision }),
  // 任务状态上报（busy 切换时通知主进程，用于托盘徽标 + 完成提醒）
  reportBusy: (busy) => ipcRenderer.send('card-busy', busy),
  // 个人记忆库
  memoryRead: () => ipcRenderer.invoke('memory-read'),
  memoryWrite: (text) => ipcRenderer.invoke('memory-write', text),
  // 剪贴板
  readClipboard: () => ipcRenderer.invoke('read-clipboard'),
  onFillInput: (cb) => ipcRenderer.on('fill-input', (_e, text) => cb(text)),
  // 待办
  todoList: () => ipcRenderer.invoke('todo-list'),
  todoAdd: (item) => ipcRenderer.invoke('todo-add', item),
  todoToggle: (id) => ipcRenderer.invoke('todo-toggle', id),
  todoDelete: (id) => ipcRenderer.invoke('todo-delete', id),
  todoClearDone: () => ipcRenderer.invoke('todo-clear-done'),
  notifyTodosUpdated: () => ipcRenderer.send('todos-updated'),
  onTodosUpdated: (cb) => ipcRenderer.on('todos-updated', () => cb()),
  // 邮件摘要
  triggerEmailSummary: () => ipcRenderer.invoke('trigger-email-summary'),
  mailGetFull: (msgId) => ipcRenderer.invoke('mail-get-full', msgId),
  mailReplyCard: (msgId) => ipcRenderer.invoke('mail-reply-card', { msgId }),
  mailViewData: (msgId) => ipcRenderer.invoke('mail-view-data', msgId),
  openMailView: (msgId) => ipcRenderer.invoke('open-mail-view', msgId),
  emailTest: () => ipcRenderer.invoke('email-test'),
  smtpTest:  () => ipcRenderer.invoke('smtp-test'),
  openMailCenter: (tab) => ipcRenderer.invoke('open-mail-center', tab),
  mailList: (opts) => ipcRenderer.invoke('mail-list', opts),
  mailMarkRead: (ids) => ipcRenderer.invoke('mail-mark-read', ids),
  mailArchive: (ids) => ipcRenderer.invoke('mail-archive', ids),
  // 发件箱(发信安全闸门)
  openOutbox:    () => ipcRenderer.invoke('open-outbox'),
  outboxList:    () => ipcRenderer.invoke('outbox-list'),
  outboxCancel:  (id) => ipcRenderer.invoke('outbox-cancel', id),
  outboxSendNow: (id) => ipcRenderer.invoke('outbox-send-now', id),
  onOutboxUpdated: (cb) => ipcRenderer.on('outbox-updated', () => cb()),
  // 内嵌浏览器
  openBrowser:          (url) => ipcRenderer.invoke('open-browser', url),
  browserNavigate:      (url) => ipcRenderer.invoke('browser-navigate', url),
  browserMenuOverlay:   (on)  => ipcRenderer.send('browser-menu-overlay', !!on),
  browserSettingsOverlay: (on) => ipcRenderer.send('browser-settings-overlay', !!on),
  browserBack:          ()    => ipcRenderer.send('browser-back'),
  browserForward:       ()    => ipcRenderer.send('browser-forward'),
  browserReload:        ()    => ipcRenderer.send('browser-reload'),
  browserDevTools:      ()    => ipcRenderer.send('browser-devtools'),
  browserNoCache:       (on)  => ipcRenderer.invoke('browser-no-cache', !!on),
  browserNewTab:        (url) => ipcRenderer.send('browser-new-tab', url),
  browserCloseTab:      (id)  => ipcRenderer.send('browser-close-tab', id),
  browserActivateTab:   (id)  => ipcRenderer.send('browser-activate-tab', id),
  browserSetDevice:     (key) => ipcRenderer.send('browser-set-device', key),
  browserRotate:        ()    => ipcRenderer.send('browser-rotate'),
  browserZoom:          (dir) => ipcRenderer.send('browser-zoom', dir),
  browserConsoleResize: (h)   => ipcRenderer.send('browser-console-resize', h),
  browserFind:          (text, findNext, forward) => ipcRenderer.send('browser-find', { text, findNext, forward }),
  browserFindStop:      ()    => ipcRenderer.send('browser-find-stop'),
  browserScreenshot:    (full) => ipcRenderer.invoke('browser-screenshot', full),
  browserAnalyze:       ()    => ipcRenderer.invoke('browser-analyze'),
  // 网络面板
  browserNetGet:        (id)  => ipcRenderer.invoke('browser-net-get', id),
  browserNetClear:      ()    => ipcRenderer.send('browser-net-clear'),
  browserNetPreserve:   (on)  => ipcRenderer.send('browser-net-preserve', on),
  // 元素拾取 + 复制
  browserPickElement:   ()    => ipcRenderer.invoke('browser-pick-element'),
  browserCopy:          (text) => ipcRenderer.invoke('browser-copy', text),
  browserReveal:        (filePath) => ipcRenderer.send('browser-reveal', filePath),
  browserRecStart:      ()    => ipcRenderer.invoke('browser-rec-start'),
  browserRecStop:       ()    => ipcRenderer.invoke('browser-rec-stop'),
  browserRecSetExpectation: (recId, text) => ipcRenderer.invoke('browser-rec-set-expectation', { recId, text }),
  browserOpenRecDir:    ()    => ipcRenderer.send('browser-open-rec-dir'),
  browserRollback:      (opts) => ipcRenderer.invoke('browser-rollback-changes', opts || {}),
  currentDiff:          ()    => ipcRenderer.invoke('current-diff'),
  browserRecList:       ()    => ipcRenderer.invoke('browser-rec-list'),
  browserRecUpdate:     (id, patch) => ipcRenderer.invoke('browser-rec-update', { id, patch }),
  browserRecDelete:     (id)  => ipcRenderer.invoke('browser-rec-delete', id),
  browserRecReplayStored:(id) => ipcRenderer.invoke('browser-rec-replay-stored', id),
  onBrowserVerifyResult:(cb)  => ipcRenderer.on('wf-verify-result', (_e, p) => cb(p)),
  browserHistory:       ()    => ipcRenderer.sendSync('get-browser-history'),
  browserReorderTabs:   (ids) => ipcRenderer.send('browser-reorder-tabs', ids),
  onBrowserDownload:    (cb)  => ipcRenderer.on('browser-download', (_e, p) => cb(p)),
  browserEval:          (expr) => ipcRenderer.invoke('browser-eval', expr),
  browserVerify:        ()    => ipcRenderer.invoke('browser-verify'),
  // 工作台分隔条（左 Agent / 右浏览器）
  browserSplit:         (arg) => ipcRenderer.send('browser-split', arg),
  onBrowserSplitSet:    (cb)  => ipcRenderer.on('browser-split-set', (_e, w) => cb(w)),
  onBrowserTabs:            (cb) => ipcRenderer.on('browser-tabs',             (_e, p) => cb(p)),
  onBrowserNav:             (cb) => ipcRenderer.on('browser-nav',              (_e, p) => cb(p)),
  onBrowserConsoleAdd:      (cb) => ipcRenderer.on('browser-console-add',      (_e, p) => cb(p)),
  onBrowserConsoleSnapshot: (cb) => ipcRenderer.on('browser-console-snapshot', (_e, p) => cb(p)),
  onBrowserBadge:           (cb) => ipcRenderer.on('browser-badge',            (_e, p) => cb(p)),
  onBrowserNetAdd:          (cb) => ipcRenderer.on('browser-net-add',          (_e, p) => cb(p)),
  onBrowserNetSnapshot:     (cb) => ipcRenderer.on('browser-net-snapshot',     (_e, p) => cb(p)),
  onBrowserFindResult:      (cb) => ipcRenderer.on('browser-find-result',      (_e, p) => cb(p)),
  onBrowserFocusUrl:        (cb) => ipcRenderer.on('browser-focus-url',        () => cb()),
  onBrowserOpenFind:        (cb) => ipcRenderer.on('browser-open-find',        () => cb()),
  // orb 窗口控制
  setOrbMousePassthrough: (pass) => ipcRenderer.send('orb-passthrough', pass),
  moveOrbBy: (dx, dy) => ipcRenderer.send('orb-move', { dx, dy }),
  dragOrb: (dx, dy) => ipcRenderer.send('orb-drag', { dx, dy }),
  snapOrbToCorner: () => ipcRenderer.send('orb-snap'),
  toggleOrbInput: (mode) => ipcRenderer.invoke('toggle-orb-input', mode),
  closeOrbInput: () => ipcRenderer.invoke('close-orb-input'),
  onOrbState: (cb) => ipcRenderer.on('orb-state', (_e, state) => cb(state)),
  onOrbWake: (cb) => ipcRenderer.on('orb-wake', () => cb()),
})
